// Trabzon ve Rize okul listeleri - bilgi/iletişim formu
export const trabzonOkullari = [
  'TRABZON - AKCAABAT - Akçaabat Bilim ve Sanat Merkezi',
  'TRABZON - AKCAABAT - Akçaabat Rehberlik ve Araştırma Merkezi',
  'TRABZON - AKCAABAT - Demirkapı İlkokulu',
  'TRABZON - AKCAABAT - Sarıtaş Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - AKCAABAT - Sarıtaş Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - AKCAABAT - Sarıtaş Özel Eğitim Uygulama Okulu III. Kademe',
  'TRABZON - AKCAABAT - Söğütlü Fatih İlkokulu',
  'TRABZON - AKÇAABAT - 100.Yıl İlkokulu',
  'TRABZON - AKÇAABAT - 17 Şubat Anadolu Lisesi',
  'TRABZON - AKÇAABAT - 23 Nisan İlkokulu',
  'TRABZON - AKÇAABAT - Abdullah Fazıl Ağanoğlu İlkokulu',
  'TRABZON - AKÇAABAT - Ağaçlı Ortaokulu',
  'TRABZON - AKÇAABAT - Akçaabat Anadolu İmam Hatip Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Anaokulu',
  'TRABZON - AKÇAABAT - Akçaabat Atatürk Turizm Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Borsa İstanbul Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Fen Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Güzel Sanatlar Ortaokulu',
  'TRABZON - AKÇAABAT - Akçaabat Hakkı Zeki Başaran Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - AKÇAABAT - Akçaabat Halk Eğitimi Merkezi',
  'TRABZON - AKÇAABAT - Akçaabat İbni Sina Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Mesleki Eğitim Merkezi',
  'TRABZON - AKÇAABAT - Akçaabat Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Akçaabat Yıldızlı Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Akçakale Anaokulu',
  'TRABZON - AKÇAABAT - Akçaköy İlkokulu',
  'TRABZON - AKÇAABAT - Akçaköy Ortaokulu',
  'TRABZON - AKÇAABAT - Akpınar Ortaokulu',
  'TRABZON - AKÇAABAT - Atatürk İlkokulu',
  'TRABZON - AKÇAABAT - Aydın İlkokulu',
  'TRABZON - AKÇAABAT - Cumhuriyet Ortaokulu',
  'TRABZON - AKÇAABAT - Çiçeklidüz İlkokulu',
  'TRABZON - AKÇAABAT - Darıca İlkokulu',
  'TRABZON - AKÇAABAT - Darıca Ortaokulu',
  'TRABZON - AKÇAABAT - Demirci İlkokulu',
  'TRABZON - AKÇAABAT - Demirci Ortaokulu',
  'TRABZON - AKÇAABAT - Demirkapı Ortaokulu',
  'TRABZON - AKÇAABAT - Derecik Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Derecik İlkokulu',
  'TRABZON - AKÇAABAT - Derecik Ortaokulu',
  'TRABZON - AKÇAABAT - Doğanköy Anaokulu',
  'TRABZON - AKÇAABAT - Doğanköy İlkokulu',
  'TRABZON - AKÇAABAT - Doğanköy Ortaokulu',
  'TRABZON - AKÇAABAT - Dörtyol Ortaokulu',
  'TRABZON - AKÇAABAT - Erikli İlkokulu',
  'TRABZON - AKÇAABAT - Fevzipaşa İlkokulu',
  'TRABZON - AKÇAABAT - Hakkı Altıntaş Ortaokulu',
  'TRABZON - AKÇAABAT - Hasan Saka İlkokulu',
  'TRABZON - AKÇAABAT - Hasan Saka Ortaokulu',
  'TRABZON - AKÇAABAT - Işıklar Çok Programlı Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Işıklar İlkokulu',
  'TRABZON - AKÇAABAT - Işıklar Ortamahalle İlkokulu',
  'TRABZON - AKÇAABAT - Işıklar Ortamahalle Ortaokulu',
  'TRABZON - AKÇAABAT - Işıklar Ortaokulu',
  'TRABZON - AKÇAABAT - İbrahim Erdemoğlu Spor Lisesi',
  'TRABZON - AKÇAABAT - İbrahim Erdemoğlu Spor Ortaokulu',
  'TRABZON - AKÇAABAT - Kaleönü Murat Köse İlkokulu',
  'TRABZON - AKÇAABAT - Kaleönü Murat Köse Ortaokulu',
  'TRABZON - AKÇAABAT - Kavaklı İlkokulu',
  'TRABZON - AKÇAABAT - Kavaklı Ortaokulu',
  'TRABZON - AKÇAABAT - Mecit Pirhasoğlu İlkokulu',
  'TRABZON - AKÇAABAT - Mersin Şehit Engin Saraç İlkokulu',
  'TRABZON - AKÇAABAT - Mersin Şehit Engin Saraç Ortaokulu',
  'TRABZON - AKÇAABAT - Meşeli İlkokulu',
  'TRABZON - AKÇAABAT - Meşeli Ortaokulu',
  'TRABZON - AKÇAABAT - Metinkale İlkokulu',
  'TRABZON - AKÇAABAT - Metinkale Ortaokulu',
  'TRABZON - AKÇAABAT - Mevlüt Selami Yardım Ortaokulu',
  'TRABZON - AKÇAABAT - MİNİK KALPLER ANAOKULU',
  'TRABZON - AKÇAABAT - Osmanbaba İlkokulu',
  'TRABZON - AKÇAABAT - Osmanbaba Ortaokulu',
  'TRABZON - AKÇAABAT - Salacık İlkokulu',
  'TRABZON - AKÇAABAT - Salacık Ortaokulu',
  'TRABZON - AKÇAABAT - Sarıtaş İmam Hatip Ortaokulu',
  'TRABZON - AKÇAABAT - Sebat İlkokulu',
  'TRABZON - AKÇAABAT - Söğütlü Anaokulu',
  'TRABZON - AKÇAABAT - Söğütlü Esentepe Anadolu Lisesi',
  'TRABZON - AKÇAABAT - SÖĞÜTLÜ İLKOKULU',
  'TRABZON - AKÇAABAT - Söğütlü Ortaokulu',
  'TRABZON - AKÇAABAT - Şehit Gökhan Uzun İmam Hatip Ortaokulu',
  'TRABZON - AKÇAABAT - Şehit Samet Uslu Kız Anadolu İmam Hatip Lisesi',
  'TRABZON - AKÇAABAT - Şinik İlkokulu',
  'TRABZON - AKÇAABAT - Trabzon Akçaabat Güzel Sanatlar Lisesi',
  'TRABZON - AKÇAABAT - Uğurlu İlkokulu',
  'TRABZON - AKÇAABAT - Vakıfbank Merkez İlkokulu',
  'TRABZON - AKÇAABAT - Yaylacık Anaokulu',
  'TRABZON - AKÇAABAT - Yaylacık İlkokulu',
  'TRABZON - AKÇAABAT - Yaylacık Ortaokulu',
  'TRABZON - AKÇAABAT - Yıldızlı Anaokulu',
  'TRABZON - AKÇAABAT - Yıldızlı TOKİ İlkokulu',
  'TRABZON - AKÇAABAT - Yıldızlı TOKİ Ortaokulu',
  'TRABZON - ARAKLI - Araklı Anadolu İmam Hatip Lisesi',
  'TRABZON - ARAKLI - Araklı Anadolu Lisesi',
  'TRABZON - ARAKLI - Araklı Bereketli İmam Hatip Ortaokulu',
  'TRABZON - ARAKLI - Araklı Bilim ve Sanat Merkezi',
  'TRABZON - ARAKLI - Araklı Halk Eğitimi Merkezi',
  'TRABZON - ARAKLI - Araklı Mehmet Akif Ersoy Anadolu Lisesi',
  'TRABZON - ARAKLI - Araklı Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - ARAKLI - Atatürk Ortaokulu',
  'TRABZON - ARAKLI - Cumhuriyet İlkokulu',
  'TRABZON - ARAKLI - Çankaya İlkokulu',
  'TRABZON - ARAKLI - Çankaya Ortaokulu',
  'TRABZON - ARAKLI - Değirmencik İlkokulu',
  'TRABZON - ARAKLI - Değirmencik Ortaokulu',
  'TRABZON - ARAKLI - ERENLER İLKOKULU',
  'TRABZON - ARAKLI - ERENLER İMAM HATİP ORTAOKULU',
  'TRABZON - ARAKLI - Hamit Özdağ İmam Hatip Ortaokulu',
  'TRABZON - ARAKLI - Hamit Özdağ Kız Anadolu İmam Hatip Lisesi',
  'TRABZON - ARAKLI - İstanbul Ticaret Odası Şehit Er Zeki Ayvenli İmam Hatip Ortaokulu',
  'TRABZON - ARAKLI - Merkez Anaokulu',
  'TRABZON - ARAKLI - Merkez İlkokulu',
  'TRABZON - ARAKLI - Muhittin Öztürk Saffet Çebi İlkokulu',
  'TRABZON - ARAKLI - Muhittin Öztürk Saffet Çebi Ortaokulu',
  'TRABZON - ARAKLI - Saffet Çebi Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ARAKLI - Taştepe İlkokulu',
  'TRABZON - ARAKLI - Taştepe Ortaokulu',
  'TRABZON - ARAKLI - Yeşilce İlkokulu',
  'TRABZON - ARAKLI - Yeşilce Ortaokulu',
  'TRABZON - ARAKLI - Yeşilyurt İlkokulu',
  'TRABZON - ARAKLI - Yeşilyurt Ortaokulu',
  'TRABZON - ARAKLI - Yılmaz Çebi İlkokulu',
  'TRABZON - ARAKLI - Yılmaz Çebi Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ARAKLI - Yılmaz Çebi Ortaokulu',
  'TRABZON - ARSİN - Arsin Anadolu Lisesi',
  'TRABZON - ARSİN - Arsin Anaokulu',
  'TRABZON - ARSİN - Arsin Halk Eğitimi Merkezi',
  'TRABZON - ARSİN - Arsin İmam Hatip Ortaokulu',
  'TRABZON - ARSİN - Arsin Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ARSİN - Arsin Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
  'TRABZON - ARSİN - Arsin Yeşilce Özel Eğitim Meslek Okulu',
  'TRABZON - ARSİN - Atatürk İlkokulu',
  'TRABZON - ARSİN - Atatürk Ortaokulu',
  'TRABZON - ARSİN - Atayurt Alparslan İlkokulu',
  'TRABZON - ARSİN - Atayurt İmam Hatip Ortaokulu',
  'TRABZON - ARSİN - Cumhuriyet İlkokulu',
  'TRABZON - ARSİN - Cumhuriyet Ortaokulu',
  'TRABZON - ARSİN - Kuzguncuk Cemal Azmi Bey İlkokulu',
  'TRABZON - ARSİN - Kuzguncuk Cemal Azmi Bey Ortaokulu',
  'TRABZON - ARSİN - Mahmut Taviloğlu İlkokulu',
  'TRABZON - ARSİN - Mehmet Akif Ersoy İlkokulu',
  'TRABZON - ARSİN - Mehmet Akif Ersoy Ortaokulu',
  'TRABZON - ARSİN - Mehmet Rüştü Aşıkkutlu Anadolu İmam Hatip Lisesi',
  'TRABZON - ARSİN - Organize Sanayi Bölgesi (OSB) Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ARSİN - Şehit Fahreddin Sarı Ortaokulu',
  'TRABZON - ARSİN - Yeşilköy Şehit Haydar Arslan İlkokulu',
  'TRABZON - ARSİN - Yeşilköy Şehit Haydar Arslan Ortaokulu',
  'TRABZON - ARSİN - Yeşilyalı İbni Sina İlkokulu',
  'TRABZON - ARSİN - Yeşilyalı İbni Sina Ortaokulu',
  'TRABZON - ARSİN - Yeşilyalı İmam Hatip Ortaokulu',
  'TRABZON - BEŞİKDÜZÜ - Ahmet Gün Anadolu İmam Hatip Lisesi',
  'TRABZON - BEŞİKDÜZÜ - Akkese İlkokulu',
  'TRABZON - BEŞİKDÜZÜ - Akkese Ortaokulu',
  'TRABZON - BEŞİKDÜZÜ - Atatürk Anaokulu',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Adalet Meslekî Eğitim Merkezi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Anadolu Lisesi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Borsa İstanbul Fen Lisesi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Farabi Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Fatih Ticaret Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Halk Eğitimi Merkezi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü İmam Hatip Ortaokulu',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Sabancı Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Sevim - Nerim Demircioğlu Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - BEŞİKDÜZÜ - Beşikdüzü Sevim - Nerim Demircioğlu Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - BEŞİKDÜZÜ - Çeşmeönü İlkokulu',
  'TRABZON - BEŞİKDÜZÜ - Çeşmeönü Ortaokulu',
  'TRABZON - BEŞİKDÜZÜ - Merkez İlkokulu',
  'TRABZON - BEŞİKDÜZÜ - Merkez Ortaokulu',
  'TRABZON - BEŞİKDÜZÜ - Şehit Öğretmen Gürhan Yardım İlkokulu',
  'TRABZON - BEŞİKDÜZÜ - Şehit Öğretmen Gürhan Yardım Ortaokulu',
  'TRABZON - BEŞİKDÜZÜ - Zübeyde Hanım Anaokulu',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Anadolu Lisesi',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Anaokulu',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Halk Eğitimi Merkezi',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Ortaokulu',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - ÇARŞIBAŞI - Çarşıbaşı Yavuz İmam Hatip Ortaokulu',
  'TRABZON - ÇARŞIBAŞI - Fener Şehit Muhammet Türk İlkokulu',
  'TRABZON - ÇARŞIBAŞI - Gazi İlkokulu',
  'TRABZON - ÇARŞIBAŞI - İsmail Çavuş Anadolu İmam Hatip Lisesi',
  'TRABZON - ÇARŞIBAŞI - İsmail Çavuş İmam Hatip Ortaokulu',
  'TRABZON - ÇARŞIBAŞI - Kadıköy İlkokulu',
  'TRABZON - ÇARŞIBAŞI - Kadıköy Ortaokulu',
  'TRABZON - ÇARŞIBAŞI - Kerem Mahalle Ortaokulu',
  'TRABZON - ÇARŞIBAŞI - Kovanlıköy İlkokulu',
  'TRABZON - ÇARŞIBAŞI - Şahinli İlkokulu',
  'TRABZON - ÇARŞIBAŞI - Yavuzköy Fatih İlkokulu',
  'TRABZON - ÇARŞIBAŞI - Yavuzköy Fatih Ortaokulu',
  'TRABZON - ÇARŞIBAŞI - Yavuzköy İlkokulu',
  'TRABZON - ÇARŞIBAŞI - Yavuzköy Ortaokulu',
  'TRABZON - ÇAYKARA - Cevdet Sunay Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ÇAYKARA - Çaykara Anadolu Lisesi',
  'TRABZON - ÇAYKARA - Çaykara Çok Programlı Anadolu Lisesi',
  'TRABZON - ÇAYKARA - Çaykara Fatma Bilge Anaokulu',
  'TRABZON - ÇAYKARA - Çaykara Halk Eğitimi Merkezi',
  'TRABZON - ÇAYKARA - Çaykara Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - ÇAYKARA - Hüseyin Vehbi Fettahoğlu İlkokulu',
  'TRABZON - ÇAYKARA - Karaçam İlkokulu',
  'TRABZON - ÇAYKARA - Karaçam Ortaokulu',
  'TRABZON - ÇAYKARA - Şehit Ahmet Çamur Anadolu İmam Hatip Lisesi',
  'TRABZON - ÇAYKARA - Şehit Mehmet Aygün İlkokulu',
  'TRABZON - ÇAYKARA - Şehit Mehmet Aygün İmam Hatip Ortaokulu',
  'TRABZON - ÇAYKARA - Taşkıran İmam Hatip Ortaokulu',
  'TRABZON - ÇAYKARA - Taşkıran Mustafa Özer Ortaokulu',
  'TRABZON - ÇAYKARA - Zeki Bilge İlkokulu',
  'TRABZON - ÇAYKARA - Zeki Bilge Ortaokulu',
  'TRABZON - DERNEKPAZARI - Atatürk İlkokulu',
  'TRABZON - DERNEKPAZARI - Atatürk Ortaokulu',
  'TRABZON - DERNEKPAZARI - Dernekpazarı Halk Eğitimi Merkezi',
  'TRABZON - DERNEKPAZARI - Dernekpazarı İmam Hatip Ortaokulu',
  'TRABZON - DERNEKPAZARI - Hasan Cansız Kom Çok Programlı Anadolu Lisesi',
  'TRABZON - DERNEKPAZARI - İbrahim Ağa Anaokulu',
  'TRABZON - DÜZKÖY - Alazlı İlkokulu',
  'TRABZON - DÜZKÖY - Alazlı Ortaokulu',
  'TRABZON - DÜZKÖY - Aykut Lütfü Ofluoğlu İlkokulu',
  'TRABZON - DÜZKÖY - Aykut Lütfü Ofluoğlu Ortaokulu',
  'TRABZON - DÜZKÖY - Çal İlkokulu',
  'TRABZON - DÜZKÖY - Çal Ortaokulu',
  'TRABZON - DÜZKÖY - Çamlıca İlkokulu',
  'TRABZON - DÜZKÖY - Çamlıca Ortaokulu',
  'TRABZON - DÜZKÖY - Çayırbağı Çok Programlı Anadolu Lisesi',
  'TRABZON - DÜZKÖY - Çayırbağı İlkokulu',
  'TRABZON - DÜZKÖY - Çayırbağı İmam Hatip Ortaokulu',
  'TRABZON - DÜZKÖY - Çayırbağı Ortaokulu',
  'TRABZON - DÜZKÖY - Çayırbağı Yusuflu İlkokulu',
  'TRABZON - DÜZKÖY - Doğankaya İlkokulu',
  'TRABZON - DÜZKÖY - Doğankaya Ortaokulu',
  'TRABZON - DÜZKÖY - Düzalan İlkokulu',
  'TRABZON - DÜZKÖY - Düzalan Ortaokulu',
  'TRABZON - DÜZKÖY - Düzköy Anadolu Lisesi',
  'TRABZON - DÜZKÖY - Düzköy Halk Eğitimi Merkezi',
  'TRABZON - DÜZKÖY - Düzköy Metin Onur Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - DÜZKÖY - Düzköy Metin Onur Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - DÜZKÖY - Düzköy Nazım Kayhan Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - DÜZKÖY - Gökçeler Ortaokulu',
  'TRABZON - DÜZKÖY - Gürgendağ İlkokulu',
  'TRABZON - DÜZKÖY - Gürgendağ Ortaokulu',
  'TRABZON - DÜZKÖY - H.Mehmet Ofluoğlu İlkokulu',
  'TRABZON - DÜZKÖY - H.Mehmet Ofluoğlu Ortaokulu',
  'TRABZON - DÜZKÖY - Haçkalı Baba İmam Hatip Ortaokulu',
  'TRABZON - DÜZKÖY - Lütfü Ofluoğlu Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - DÜZKÖY - Mehmet Akkaya Anadolu İmam Hatip Lisesi',
  'TRABZON - DÜZKÖY - Minik Kalpler Anaokulu',
  'TRABZON - DÜZKÖY - Taşocağı İlkokulu',
  'TRABZON - HAYRAT - Balaban Hacısalih Musaoğlu İlkokulu',
  'TRABZON - HAYRAT - Balaban Hacısalih Musaoğlu Ortaokulu',
  'TRABZON - HAYRAT - Hayrat Borsa İstanbul Çok Programlı Anadolu Lisesi',
  'TRABZON - HAYRAT - Hayrat Borsa İstanbul İlkokulu',
  'TRABZON - HAYRAT - Hayrat Borsa İstanbul Ortaokulu',
  'TRABZON - HAYRAT - Hayrat İmam Hatip Ortaokulu',
  'TRABZON - HAYRAT - Hayrat Nuhoğlu Vakfı Ramiz Yıldırım Halk Eğitimi Merkezi',
  'TRABZON - HAYRAT - Taflancık Fazlı Rıza Zengin İlkokulu',
  'TRABZON - KÖPRÜBAŞI - Adnan Kahveci İlkokulu',
  'TRABZON - KÖPRÜBAŞI - Adnan Kahveci İmam Hatip Ortaokulu',
  'TRABZON - KÖPRÜBAŞI - Köprübaşı Çok Programlı Anadolu Lisesi',
  'TRABZON - KÖPRÜBAŞI - Köprübaşı Hatice Aslan Aksoy Anaokulu',
  'TRABZON - KÖPRÜBAŞI - Merkez İlkokulu',
  'TRABZON - KÖPRÜBAŞI - Merkez Ortaokulu',
  'TRABZON - KÖPRÜBAŞI - Trabzon Köprübaşı Halk Eğitimi Merkezi',
  'TRABZON - MAÇKA - Başar İlkokulu',
  'TRABZON - MAÇKA - Başar Ortaokulu',
  'TRABZON - MAÇKA - Ce-zi-ne Kardeşler İlkokulu',
  'TRABZON - MAÇKA - Cumhuriyet Ortaokulu',
  'TRABZON - MAÇKA - Çatak İlkokulu',
  'TRABZON - MAÇKA - Çatak Ortaokulu',
  'TRABZON - MAÇKA - Esiroğlu Kenan Oltan Anadolu Lisesi',
  'TRABZON - MAÇKA - Esiroğlu Şehit Er Mehmet Akyüz İlkokulu',
  'TRABZON - MAÇKA - Kayalar Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - MAÇKA - Konaklar İlkokulu',
  'TRABZON - MAÇKA - Konaklar Ortaokulu',
  'TRABZON - MAÇKA - Maçka Anaokulu',
  'TRABZON - MAÇKA - Maçka Esiroğlu Şehit Er Mehmet Akyüz Ortaokulu',
  'TRABZON - MAÇKA - Maçka Halk Eğitimi Merkezi',
  'TRABZON - MAÇKA - Maçka Mehmet Akif Ersoy Anadolu Lisesi',
  'TRABZON - MAÇKA - Maçka Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - MAÇKA - Maçka Şehit Eren Bülbül Anadolu İmam Hatip Lisesi',
  'TRABZON - MAÇKA - Maçka Tevfik İleri İmam Hatip Ortaokulu',
  'TRABZON - OF - 28 Şubat İlkokulu',
  'TRABZON - OF - Ali Yeşilyurt İmam Hatip Ortaokulu',
  'TRABZON - OF - Bölümlü Mehmet Akif Ersoy İlkokulu',
  'TRABZON - OF - Bölümlü Şehit İhsan Yıldız Ortaokulu',
  'TRABZON - OF - Cumapazarı İlkokulu',
  'TRABZON - OF - Cumapazarı Ortaokulu',
  'TRABZON - OF - Eskipazar İlkokulu',
  'TRABZON - OF - Eskipazar Ortaokulu',
  'TRABZON - OF - Fatih Sultan Mehmet Ortaokulu',
  'TRABZON - OF - Gürpınar İlkokulu',
  'TRABZON - OF - Gürpınar İmam Hatip Ortaokulu',
  'TRABZON - OF - Hacıahmetoğlu Ortaokulu',
  'TRABZON - OF - İhsan Karadeniz İlkokulu',
  'TRABZON - OF - İhsan Karadeniz Ortaokulu',
  'TRABZON - OF - İsmail Yıldırım İlkokulu',
  'TRABZON - OF - Kıyıcık İlkokulu',
  'TRABZON - OF - Kıyıcık Ortaokulu',
  'TRABZON - OF - Kireçli Dursun Dumangöz İlkokulu',
  'TRABZON - OF - Kireçli Dursun Dumangöz Ortaokulu',
  'TRABZON - OF - Mikdat Sarıalioğlu Ortaokulu',
  'TRABZON - OF - Of Anadolu İmam Hatip Lisesi',
  'TRABZON - OF - Of Bilim ve Sanat Merkezi',
  'TRABZON - OF - Of Fen Lisesi',
  'TRABZON - OF - Of Hacı Mehmet Bahattin Ulusoy Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - OF - Of Halk Eğitimi Merkezi',
  'TRABZON - OF - Of Mesleki Eğitim Merkezi',
  'TRABZON - OF - Of Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - OF - Of Rehberlik ve Araştırma Merkezi',
  'TRABZON - OF - Pınaraltı İlkokulu',
  'TRABZON - OF - Pınaraltı Ortaokulu',
  'TRABZON - OF - Serince Şehit Fahrettin Yavuz İmam Hatip Ortaokulu',
  'TRABZON - OF - Şehit Ahmet Türkkan Çok Programlı Anadolu Lisesi',
  'TRABZON - OF - Şehit Hüsnü Uyan Anaokulu',
  'TRABZON - OF - Şehit Necmi Çakır Anadolu Lisesi',
  'TRABZON - OF - Şehit Öğretmen Ali Bulut İlkokulu',
  'TRABZON - OF - Taşhan Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - OF - Yakup Türköz Özel Eğitim Meslek Okulu',
  'TRABZON - ORTAHİSAR - 100.Yıl İlkokulu',
  'TRABZON - ORTAHİSAR - 24 Şubat Ortaokulu',
  'TRABZON - ORTAHİSAR - 80. Yıl Çok Programlı Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - 88.Yıl Cumhuriyet Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Affan Kitapçıoğlu Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Ahmet Saka İlkokulu',
  'TRABZON - ORTAHİSAR - Ahmet Yahya Subaşı İlkokulu',
  'TRABZON - ORTAHİSAR - Ahmet Yahya Subaşı Ortaokulu',
  'TRABZON - ORTAHİSAR - Akoluk İlkokulu',
  'TRABZON - ORTAHİSAR - Akoluk Ortaokulu',
  'TRABZON - ORTAHİSAR - Akyazı İlkokulu',
  'TRABZON - ORTAHİSAR - Akyazı Ortaokulu',
  'TRABZON - ORTAHİSAR - Ali Kemal Aktürk İlkokulu',
  'TRABZON - ORTAHİSAR - Ali Soylu Anadolu İmam Hatip Lisesi',
  'TRABZON - ORTAHİSAR - Aliye Aşırbaylı Anaokulu',
  'TRABZON - ORTAHİSAR - Ata İlkokulu',
  'TRABZON - ORTAHİSAR - Ata Ortaokulu',
  'TRABZON - ORTAHİSAR - Atatürk İlkokulu',
  'TRABZON - ORTAHİSAR - Atatürk Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Atatürk Ortaokulu',
  'TRABZON - ORTAHİSAR - Aydınlıkevler İmam Hatip Ortaokulu',
  'TRABZON - ORTAHİSAR - Ayfer Karakullukçu İlkokulu',
  'TRABZON - ORTAHİSAR - Bahçecik İmam Hatip Ortaokulu',
  'TRABZON - ORTAHİSAR - Bedri Rahmi Eyüboğlu İlkokulu',
  'TRABZON - ORTAHİSAR - Bedri Rahmi Eyüboğlu Ortaokulu',
  'TRABZON - ORTAHİSAR - Bener Cordan Ortaokulu',
  'TRABZON - ORTAHİSAR - Beşirli Anaokulu',
  'TRABZON - ORTAHİSAR - Beşirli Borsa İstanbul Ortaokulu',
  'TRABZON - ORTAHİSAR - Borsa İstanbul Kız Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Bostancı İlkokulu',
  'TRABZON - ORTAHİSAR - Bostancı Ortaokulu',
  'TRABZON - ORTAHİSAR - Boztepe İlkokulu',
  'TRABZON - ORTAHİSAR - Cudibey Ortaokulu',
  'TRABZON - ORTAHİSAR - Cumhuriyet İlkokulu',
  'TRABZON - ORTAHİSAR - Cumhuriyet Ortaokulu',
  'TRABZON - ORTAHİSAR - Çağlayan Adnan Menderes Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Çağlayan İmam Hatip Ortaokulu',
  'TRABZON - ORTAHİSAR - Çağlayan Merkez Şehit Gürcan Bayrak İlkokulu',
  'TRABZON - ORTAHİSAR - Çağlayan Merkez Şehit Gürcan Bayrak Ortaokulu',
  'TRABZON - ORTAHİSAR - Çamlık İşitme Engelliler Ortaokulu',
  'TRABZON - ORTAHİSAR - ÇAMOBA ANAOKULU',
  'TRABZON - ORTAHİSAR - Çimenli İlkokulu',
  'TRABZON - ORTAHİSAR - Çimenli Ortaokulu',
  'TRABZON - ORTAHİSAR - Çukurçayır Anaokulu',
  'TRABZON - ORTAHİSAR - Çukurçayır İlkokulu',
  'TRABZON - ORTAHİSAR - ÇUKURÇAYIR MİNİK ADIMLAR ANAOKULU',
  'TRABZON - ORTAHİSAR - Çukurçayır Ortaokulu',
  'TRABZON - ORTAHİSAR - Dolaylı İlkokulu',
  'TRABZON - ORTAHİSAR - Dolaylı Ortaokulu',
  'TRABZON - ORTAHİSAR - Dumlupınar İlkokulu',
  'TRABZON - ORTAHİSAR - Dursun Ali Kurt Anadolu İmam Hatip Lisesi',
  'TRABZON - ORTAHİSAR - Düzyurt İlkokulu',
  'TRABZON - ORTAHİSAR - Düzyurt Ortaokulu',
  'TRABZON - ORTAHİSAR - Erdoğdu Anaokulu',
  'TRABZON - ORTAHİSAR - Erdoğdu Bey Ortaokulu',
  'TRABZON - ORTAHİSAR - Erdoğdu İlkokulu',
  'TRABZON - ORTAHİSAR - ERDOĞDU ÖZEL EĞİTİM UYGULAMA MERKEZİ II. KADEME',
  'TRABZON - ORTAHİSAR - Erdoğdu Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - ORTAHİSAR - Fatih Anaokulu',
  'TRABZON - ORTAHİSAR - Fatih Sultan Mehmet Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Fatma Tuna Kızılay Anaokulu',
  'TRABZON - ORTAHİSAR - Gazi Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Gazipaşa Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - ORTAHİSAR - Gazipaşa Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - ORTAHİSAR - Gölçayır İlkokulu',
  'TRABZON - ORTAHİSAR - Gölçayır Ortaokulu',
  'TRABZON - ORTAHİSAR - Gülbahar Hatun Anaokulu',
  'TRABZON - ORTAHİSAR - Gürbulak İlkokulu',
  'TRABZON - ORTAHİSAR - GÜRBULAK ORTAOKULU',
  'TRABZON - ORTAHİSAR - Hami Yıldırım İlkokulu',
  'TRABZON - ORTAHİSAR - Hasan Ali Yücel İlkokulu',
  'TRABZON - ORTAHİSAR - Hasan Tahsin Kırali İlkokulu',
  'TRABZON - ORTAHİSAR - HIZIRBEY ÜLKÜ İLKOKULU',
  'TRABZON - ORTAHİSAR - Hüseyin Hüsnü Aker Anaokulu',
  'TRABZON - ORTAHİSAR - İbrahim Alemdağ Ortaokulu',
  'TRABZON - ORTAHİSAR - İskenderpaşa Ortaokulu',
  'TRABZON - ORTAHİSAR - İsmail Hakkı Bereketoğlu Anaokulu',
  'TRABZON - ORTAHİSAR - İsmetpaşa İlkokulu',
  'TRABZON - ORTAHİSAR - Kaan Dinler Anaokulu',
  'TRABZON - ORTAHİSAR - Kanuni Anadolu İmam Hatip Lisesi',
  'TRABZON - ORTAHİSAR - Kanuni Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Kanuni İlkokulu',
  'TRABZON - ORTAHİSAR - Kanuni Ortaokulu',
  'TRABZON - ORTAHİSAR - Karadeniz Özel Eğitim Meslek Okulu',
  'TRABZON - ORTAHİSAR - Karakaya İlkokulu',
  'TRABZON - ORTAHİSAR - Karakaya Ortaokulu',
  'TRABZON - ORTAHİSAR - Karbeyaz Anaokulu',
  'TRABZON - ORTAHİSAR - Kardelen Anaokulu',
  'TRABZON - ORTAHİSAR - Karlık İlkokulu',
  'TRABZON - ORTAHİSAR - Karlık Ortaokulu',
  'TRABZON - ORTAHİSAR - Karşıyaka İmam Hatip Ortaokulu',
  'TRABZON - ORTAHİSAR - Kireçhane İlkokulu',
  'TRABZON - ORTAHİSAR - Kireçhane Ortaokulu',
  'TRABZON - ORTAHİSAR - Kutlugün İlkokulu',
  'TRABZON - ORTAHİSAR - Kutlugün Ortaokulu',
  'TRABZON - ORTAHİSAR - Mahmut Celaleddin Ökten Anadolu İmam Hatip Lisesi',
  'TRABZON - ORTAHİSAR - Mehmet Akif Ersoy Ortaokulu',
  'TRABZON - ORTAHİSAR - Mimar Sinan Ortaokulu',
  'TRABZON - ORTAHİSAR - Necip Fazıl Kısakürek İmam-Hatip Ortaokulu',
  'TRABZON - ORTAHİSAR - Ortahisar Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Ortahisar Bilim ve Sanat Merkezi',
  'TRABZON - ORTAHİSAR - Ortahisar Çamlık İşitme Engelliler İlkokulu',
  'TRABZON - ORTAHİSAR - Ortahisar Çamlık Özel Eğitim Meslek Lisesi',
  'TRABZON - ORTAHİSAR - Ortahisar Halk Eğitimi Merkezi',
  'TRABZON - ORTAHİSAR - Ortahisar Mesleki Eğitim Merkezi',
  'TRABZON - ORTAHİSAR - Ortahisar Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - ORTAHİSAR - Ortahisar Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - ORTAHİSAR - Osman Altıntaş Ortaokulu',
  'TRABZON - ORTAHİSAR - Osman Kalyoncu İmam Hatip Ortaokulu',
  'TRABZON - ORTAHİSAR - Ömer Burak Terzi Özel Eğitim Anaokulu',
  'TRABZON - ORTAHİSAR - Pelitli 75. Yıl Cumhuriyet Ortaokulu',
  'TRABZON - ORTAHİSAR - Pelitli Ahmet Can Bali Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Pelitli Mareşal Fevzi Çakmak İlkokulu',
  'TRABZON - ORTAHİSAR - Pelitli Şehit Kadir Tuncer İlkokulu',
  'TRABZON - ORTAHİSAR - Pınaraltı Keleşli İlkokulu',
  'TRABZON - ORTAHİSAR - Piri Reis İlkokulu',
  'TRABZON - ORTAHİSAR - Piri Reis Ortaokulu',
  'TRABZON - ORTAHİSAR - Prof. Dr. Necmettin Erbakan Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Prof. İhsan Koz İlkokulu',
  'TRABZON - ORTAHİSAR - Soğuksu İstiklal İlkokulu',
  'TRABZON - ORTAHİSAR - Şehit Ali Yasin Erosmanoğlu Anaokulu',
  'TRABZON - ORTAHİSAR - Şehit Pilot Yüzbaşı Burak Gençcelep İlkokulu',
  'TRABZON - ORTAHİSAR - Şehit Pilot Yüzbaşı Burak Gençcelep Ortaokulu',
  'TRABZON - ORTAHİSAR - Şehit Ünal Bıçakçı Ticaret Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Temel Yaşar Çoruh İlkokulu',
  'TRABZON - ORTAHİSAR - Tevfik Serdar Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Tevfikbey Anaokulu',
  'TRABZON - ORTAHİSAR - Ticaret İlkokulu',
  'TRABZON - ORTAHİSAR - Trabzon 15 Temmuz Şehitleri Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Trabzon Anadolu İmam Hatip Lisesi',
  'TRABZON - ORTAHİSAR - Trabzon Faruk Başaran Bilim ve Sanat Merkezi',
  'TRABZON - ORTAHİSAR - Trabzon Kız Anadolu İmam Hatip Lisesi',
  'TRABZON - ORTAHİSAR - Trabzon Merkez Fen Lisesi',
  'TRABZON - ORTAHİSAR - Trabzon Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Trabzon Olgunlaşma Enstitüsü',
  'TRABZON - ORTAHİSAR - Trabzon Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - ORTAHİSAR - Trabzon Rehberlik ve Araştırma Merkezi',
  'TRABZON - ORTAHİSAR - Trabzon Sosyal Bilimler Lisesi',
  'TRABZON - ORTAHİSAR - Trabzon Spor Lisesi',
  'TRABZON - ORTAHİSAR - Uğurlu İlkokulu',
  'TRABZON - ORTAHİSAR - Uğurlu Ortaokulu',
  'TRABZON - ORTAHİSAR - Yalıncak İlkokulu',
  'TRABZON - ORTAHİSAR - YALINCAK İMAM HATİP ORTAOKULU',
  'TRABZON - ORTAHİSAR - Yalıncak Ortaokulu',
  'TRABZON - ORTAHİSAR - Yavuz Selim İlkokulu',
  'TRABZON - ORTAHİSAR - Yavuz Sultan Selim Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Yeşilova İlkokulu',
  'TRABZON - ORTAHİSAR - Yeşilova Kemal Bülbüloğlu Ortaokulu',
  'TRABZON - ORTAHİSAR - Yeşiltepe İlkokulu',
  'TRABZON - ORTAHİSAR - Yol-İş Sendikası Ortaokulu',
  'TRABZON - ORTAHİSAR - Yunus Emre Anaokulu',
  'TRABZON - ORTAHİSAR - Yunus Emre Ortaokulu',
  'TRABZON - ORTAHİSAR - Zafer Özel Eğitim Uygulama Okulu III. Kademe',
  'TRABZON - ORTAHİSAR - Zehra Kitapçıoğlu Anaokulu',
  'TRABZON - ORTAHİSAR - Zehra Kitapçıoğlu İlkokulu',
  'TRABZON - ORTAHİSAR - Zübeyde Hanım Kız Anadolu Lisesi',
  'TRABZON - ORTAHİSAR - Özel Candan Koleji',
  'TRABZON - SÜRMENE - Aşağı Aksu İlkokulu',
  'TRABZON - SÜRMENE - Aşağı Aksu Ortaokulu',
  'TRABZON - SÜRMENE - Ayşe Kırali Ortaokulu',
  'TRABZON - SÜRMENE - Cevdet Cavit Şenkaya Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - SÜRMENE - Cevher Özden Kız Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - SÜRMENE - Çamburnu Fazıloğlu Mahmut Bıçakçı Ortaokulu',
  'TRABZON - SÜRMENE - Çamburnu İlkokulu',
  'TRABZON - SÜRMENE - Çavuşlu Ali Kırali İlkokulu',
  'TRABZON - SÜRMENE - Çavuşlu Ortaokulu',
  'TRABZON - SÜRMENE - Dursun Karabacak İlkokulu',
  'TRABZON - SÜRMENE - Dursun Karabacak Ortaokulu',
  'TRABZON - SÜRMENE - Halis Çebi Mesleki Eğitim Merkezi',
  'TRABZON - SÜRMENE - Küçükdere Enver Dursun Yılmaz İlkokulu',
  'TRABZON - SÜRMENE - Küçükdere Enver Dursun Yılmaz Ortaokulu',
  'TRABZON - SÜRMENE - Ormanseven İlkokulu',
  'TRABZON - SÜRMENE - Ormanseven Ortaokulu',
  'TRABZON - SÜRMENE - Oylum İlkokulu',
  'TRABZON - SÜRMENE - Sürmene Ahmet Yılmaz Özel Eğitim Uygulama Okulu III. Kademe',
  'TRABZON - SÜRMENE - Sürmene Halk Eğitimi Merkezi',
  'TRABZON - SÜRMENE - Sürmene Hasan Sadri Yetmişbir Anadolu Lisesi',
  'TRABZON - SÜRMENE - Sürmene Hasan Tahsin Kırali Anadolu Lisesi',
  'TRABZON - SÜRMENE - Sürmene İmam Hatip Ortaokulu',
  'TRABZON - SÜRMENE - Sürmene İnci-Hamitcan Aksoy Öğretmenevi ve Akşam Sanat Okulu Müdürlüğü',
  'TRABZON - SÜRMENE - Sürmene Muratlı Özel Eğitim Anaokulu',
  'TRABZON - SÜRMENE - Sürmene Şehit Muhammet Yıldız Anadolu İmam Hatip Lisesi',
  'TRABZON - SÜRMENE - Sürmene Türk Telekom Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - SÜRMENE - Şehit Kaymakam Muhammet Fatih Safitürk İlkokulu',
  'TRABZON - SÜRMENE - Talat Orhon Anaokulu',
  'TRABZON - SÜRMENE - Yakup Kalafatoğlu İlkokulu',
  'TRABZON - SÜRMENE - Yakup Kalafatoğlu Ortaokulu',
  'TRABZON - SÜRMENE - Yardımlaşma Vakfı Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - SÜRMENE - Yardımlaşma Vakfı Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - SÜRMENE - Zübeyde Hanım Anaokulu',
  'TRABZON - ŞALPAZARI - Ali İbrahimağaoğlu Anaokulu',
  'TRABZON - ŞALPAZARI - Atatürk İlkokulu',
  'TRABZON - ŞALPAZARI - Atatürk Ortaokulu',
  'TRABZON - ŞALPAZARI - Doğancı İlkokulu',
  'TRABZON - ŞALPAZARI - Gökçeköy İlkokulu',
  'TRABZON - ŞALPAZARI - Gökçeköy Ortaokulu',
  'TRABZON - ŞALPAZARI - Simenli İlkokulu',
  'TRABZON - ŞALPAZARI - Şalpazarı Anadolu İmam Hatip Lisesi',
  'TRABZON - ŞALPAZARI - Şalpazarı Anadolu Lisesi',
  'TRABZON - ŞALPAZARI - Şalpazarı Ayten Yılmaz Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - ŞALPAZARI - Şalpazarı Halk Eğitimi Merkezi',
  'TRABZON - TONYA - 125. Yıl Anaokulu',
  'TRABZON - TONYA - 17 Şubat İlkokulu',
  'TRABZON - TONYA - 17 Şubat Ortaokulu',
  'TRABZON - TONYA - Feride-Ahmet Şener Ortaokulu',
  'TRABZON - TONYA - Hoşarlı İlkokulu',
  'TRABZON - TONYA - Hoşarlı Ortaokulu',
  'TRABZON - TONYA - Karaağaçlı İlkokulu',
  'TRABZON - TONYA - Karaağaçlı Ortaokulu',
  'TRABZON - TONYA - Necmettin Karaduman İlkokulu',
  'TRABZON - TONYA - Şehit Ayhan Güner İlkokulu',
  'TRABZON - TONYA - ŞEHİT KENAN KUMAŞ İLKOKULU',
  'TRABZON - TONYA - ŞEHİT KENAN KUMAŞ ORTAOKULU',
  'TRABZON - TONYA - Tonya Anadolu İmam Hatip Lisesi',
  'TRABZON - TONYA - Tonya Atatürk Çok Programlı Anadolu Lisesi',
  'TRABZON - TONYA - Tonya Halk Eğitimi Merkezi',
  'TRABZON - TONYA - Tonya İmam Hatip Ortaokulu',
  'TRABZON - TONYA - Tonya Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - TONYA - Tonya Şehit Soner Yıldırım Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - TONYA - Trabzon Tonya Anadolu Lisesi',
  'TRABZON - VAKFIKEBİR - Atatürk Ortaokulu',
  'TRABZON - VAKFIKEBİR - Büyükliman İlkokulu',
  'TRABZON - VAKFIKEBİR - Cumhuriyet Anaokulu',
  'TRABZON - VAKFIKEBİR - Cumhuriyet İlkokulu',
  'TRABZON - VAKFIKEBİR - Cumhuriyet Ortaokulu',
  'TRABZON - VAKFIKEBİR - Deregözü İlkokulu',
  'TRABZON - VAKFIKEBİR - Deregözü Ortaokulu',
  'TRABZON - VAKFIKEBİR - Fevziye İlkokulu',
  'TRABZON - VAKFIKEBİR - Fevziye Ortaokulu',
  'TRABZON - VAKFIKEBİR - Kemaliye Adnan Demirtürk İlkokulu',
  'TRABZON - VAKFIKEBİR - Osman Tan Ortaokulu',
  'TRABZON - VAKFIKEBİR - Ömer Nakkaş Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Anadolu İmam Hatip Lisesi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Bilim ve Sanat Merkezi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Fen Lisesi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Gülbahar Hatun Anadolu Lisesi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Halk Eğitimi Merkezi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Hikmet Kaan İmam Hatip Ortaokulu',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Mesleki Eğitim Merkezi',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Öğretmenevi ve Akşam Sanat Okulu',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Özel Eğitim Meslek Okulu',
  'TRABZON - VAKFIKEBİR - Vakfıkebir Turizm Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - VAKFIKEBİR - Yalıköy İlkokulu',
  'TRABZON - VAKFIKEBİR - Yalıköy İmam Hatip Ortaokulu',
  'TRABZON - VAKFIKEBİR - Yalıköy Ortaokulu',
  'TRABZON - YOMRA - Çamlıyurt İlkokulu',
  'TRABZON - YOMRA - Hacı Hakkı Çalık Anadolu İmam Hatip Lisesi',
  'TRABZON - YOMRA - Hafız Murat Köseoğlu İmam Hatip Ortaokulu',
  'TRABZON - YOMRA - Kaşüstü Cumhuriyet İlkokulu',
  'TRABZON - YOMRA - Kaşüstü Cumhuriyet Ortaokulu',
  'TRABZON - YOMRA - Kaşüstü Çok Programlı Anadolu Lisesi',
  'TRABZON - YOMRA - Kaşüstü İlkokulu',
  'TRABZON - YOMRA - Kaşüstü Ortaokulu',
  'TRABZON - YOMRA - Kömürcü Ortaokulu',
  'TRABZON - YOMRA - Maden Ortaokulu',
  'TRABZON - YOMRA - Merkez Anaokulu',
  'TRABZON - YOMRA - Merkez İlkokulu',
  'TRABZON - YOMRA - Merkez Ortaokulu',
  'TRABZON - YOMRA - Oymalıtepe İlkokulu',
  'TRABZON - YOMRA - Oymalıtepe Şehit Sedat Kaplan Ortaokulu',
  'TRABZON - YOMRA - Özdil Çok Programlı Anadolu Lisesi',
  'TRABZON - YOMRA - Özdil İlkokulu',
  'TRABZON - YOMRA - Özdil İmam Hatip Ortaokulu',
  'TRABZON - YOMRA - Sevim-Nerim Demircioğlu Anaokulu',
  'TRABZON - YOMRA - Temel ve Kebire Çalık İmam Hatip Ortaokulu',
  'TRABZON - YOMRA - Trabzon Yomra Fen Lisesi',
  'TRABZON - YOMRA - Vilayetler Birliği Özel Eğitim Uygulama Okulu I. Kademe',
  'TRABZON - YOMRA - Vilayetler Birliği Özel Eğitim Uygulama Okulu II. Kademe',
  'TRABZON - YOMRA - Vilayetler Birliği Özel Eğitim Uygulama Okulu III. Kademe',
  'TRABZON - YOMRA - Yavuz Selim İlkokulu',
  'TRABZON - YOMRA - Yomra Anadolu Lisesi',
  'TRABZON - YOMRA - Yomra Halk Eğitimi Merkezi',
  'TRABZON - YOMRA - Yomra Özel Eğitim Anaokulu',
  'TRABZON - MERKEZ - Özel Ana Sınav Temel Lisesi',
  'TRABZON - MERKEZ - Özel Bahçeşehir Koleji Trabzon Kampüsü',
  'TRABZON - MERKEZ - Özel Düşünür Koleji Trabzon Ortaokulu',
  'TRABZON - MERKEZ - Özel İlke Birey Okulları',
  'TRABZON - MERKEZ - Özel İpekyolu Ortaokulu',
  'TRABZON - MERKEZ - Özel Kuzey Okulları Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - MERKEZ - Özel Net Anadolu Lisesi',
  'TRABZON - MERKEZ - Özel Net Fen Lisesi',
  'TRABZON - MERKEZ - Özel TED Koleji Trabzon Kampüsü',
  'TRABZON - MERKEZ - Özel Trabzon Doğa Koleji',
  'TRABZON - MERKEZ - Özel Trabzon Mektebim Anadolu Lisesi',
  'TRABZON - MERKEZ - Özel Trabzon Mektebim Ortaokulu',
  'TRABZON - AKÇAABAT - Özel Akçaabat Sınav Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Özel Akçaabat Sınav Fen Lisesi',
  'TRABZON - AKÇAABAT - Özel Akçaabat Uğur Mesleki ve Teknik Anadolu Lisesi',
  'TRABZON - AKÇAABAT - Özel Trabzon Bil Temel Lisesi',
]

export const rizeOkullari = [
  // ARDEŞEN
  'RİZE - ARDEŞEN - Alparslan Ortaokulu',
  'RİZE - ARDEŞEN - Ardeşen Anadolu İmam Hatip Lisesi',
  'RİZE - ARDEŞEN - Ardeşen Fırtına Vadisi İrfan Tufan Karaoğlu Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ARDEŞEN - Ardeşen İmam Hatip Ortaokulu',
  'RİZE - ARDEŞEN - Ardeşen Lokman Hekim Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ARDEŞEN - Ardeşen Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ARDEŞEN - ARDEŞEN NECİP FAZIL KISAKÜREK İMAM HATİP ORTAOKULU',
  'RİZE - ARDEŞEN - Ardeşen Piri Reis Denizcilik Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ARDEŞEN - Ardeşen Şehit Ömer Halisdemir Fen Lisesi',
  'RİZE - ARDEŞEN - Işıklı 60 Yıl Ortaokulu',
  'RİZE - ARDEŞEN - Köprüköy Ortaokulu',
  'RİZE - ARDEŞEN - RABİA HATUN KIZ ANADOLU İMAM HATİP LİSESİ',
  'RİZE - ARDEŞEN - Seslıkaya Ziya Okutan Ortaokulu',
  'RİZE - ARDEŞEN - Türk Telekom Kanuni Anadolu Lisesi',
  'RİZE - ARDEŞEN - Yavuz Selim Ortaokulu',
  'RİZE - ARDEŞEN - Ardeşen Cumhuriyet İlkokulu',
  'RİZE - ARDEŞEN - Ardeşen Merkez Fatih İlkokulu',
  'RİZE - ARDEŞEN - Seslıkaya Ziya Okutan İlkokulu',
  'RİZE - ARDEŞEN - Fikri Keçeli İlkokulu',
  'RİZE - ARDEŞEN - Ardeşen Fatih İlkokulu',
  'RİZE - ARDEŞEN - Atatürk Anaokulu',
  'RİZE - ARDEŞEN - Borsa İstanbul İlkokulu',
  'RİZE - ARDEŞEN - Cumhuriyet İlkokulu',
  'RİZE - ARDEŞEN - Gazi Mustafa Kemal İlkokulu',
  'RİZE - ARDEŞEN - Işıklı 60 Yıl İlkokulu',
  'RİZE - ARDEŞEN - Köprüköy İlkokulu',
  'RİZE - ARDEŞEN - Mesut Karaoğlu İlkokulu',
  // ÇAMLIHEMŞİN
  'RİZE - ÇAMLIHEMŞİN - Atatürk Ortaokulu',
  'RİZE - ÇAMLIHEMŞİN - Çamlıhemşin Anadolu İmam Hatip Lisesi',
  'RİZE - ÇAMLIHEMŞİN - Çamlıhemşin Çok Programlı Anadolu Lisesi',
  'RİZE - ÇAMLIHEMŞİN - DİKKAYA ORTAOKULU',
  'RİZE - ÇAMLIHEMŞİN - İstanbul Ticaret Odası Şehit Binbaşı Ömer Aktuğ Ortaokulu',
  'RİZE - ÇAMLIHEMŞİN - ATATÜRK İLKOKULU',
  'RİZE - ÇAMLIHEMŞİN - DİKKAYA İLKOKULU',
  'RİZE - ÇAMLIHEMŞİN - Düzmahalle İlkokulu',
  'RİZE - ÇAMLIHEMŞİN - İstanbul Ticaret Odası Şehit Binbaşı Ömer Aktuğ İlkokulu',
  // ÇAYELİ
  'RİZE - ÇAYELİ - Ahmet Hamdi-Nurzan İshakoğlu Anadolu Lisesi',
  'RİZE - ÇAYELİ - Beyazsu Ortaokulu',
  'RİZE - ÇAYELİ - Büyükköy Ortaokulu',
  'RİZE - ÇAYELİ - Çayeli Ahmet Hamdi İshakoğlu Denizcilik Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ÇAYELİ - Çayeli Anadolu İmam Hatip Lisesi',
  'RİZE - ÇAYELİ - Çayeli Anadolu Lisesi',
  'RİZE - ÇAYELİ - Çayeli Barbaros Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ÇAYELİ - Çayeli Fen Lisesi',
  'RİZE - ÇAYELİ - Çayeli Hacı Ahmet Hamdi İshakoğlu Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ÇAYELİ - Çayeli Halk Eğitimi Merkezi',
  'RİZE - ÇAYELİ - Çayeli Kız Anadolu İmam Hatip Lisesi',
  'RİZE - ÇAYELİ - Çayeli Kız Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - ÇAYELİ - Hüseyin Rüştü Altunbaş Ortaokulu',
  'RİZE - ÇAYELİ - Kaptanpaşa İzzet Akcal Yatılı Bölge Ortaokulu',
  'RİZE - ÇAYELİ - Madenli Ortaokulu',
  'RİZE - ÇAYELİ - Merkez Atatürk Ortaokulu',
  'RİZE - ÇAYELİ - Şehit Muhammet Ambar İmam Hatip Ortaokulu',
  'RİZE - ÇAYELİ - Yamantürk Ortaokulu',
  'RİZE - ÇAYELİ - Çayeli Yamaç İlkokulu',
  'RİZE - ÇAYELİ - Hasan Yılmaz İlkokulu',
  'RİZE - ÇAYELİ - Çayeli Beyazsu İlkokulu',
  'RİZE - ÇAYELİ - 9 Mart İlkokulu',
  'RİZE - ÇAYELİ - Tunca Şehit Cumalı Ayçiçek İlkokulu',
  'RİZE - ÇAYELİ - Fikri Keçeli İlkokulu',
  'RİZE - ÇAYELİ - Beyazsu İlkokulu',
  'RİZE - ÇAYELİ - Büyükköy İlkokulu',
  'RİZE - ÇAYELİ - İshakoğlu İlkokulu',
  'RİZE - ÇAYELİ - Kaptanoğlu İlkokulu',
  'RİZE - ÇAYELİ - Kaptanpaşa İzzet Akçal İlkokulu',
  'RİZE - ÇAYELİ - Madenli ilkokulu',
  // DEREPAZARI
  'RİZE - DEREPAZARI - Adem Özdemir Anadolu Lisesi',
  'RİZE - DEREPAZARI - Ali Rıza Yılmaz Ortaokulu',
  'RİZE - DEREPAZARI - DEREPAZARI İMAM HATİP ORTAOKULU',
  'RİZE - DEREPAZARI - Derepazarı Merkez İlkokulu',
  'RİZE - DEREPAZARI - Fıçıcılar İlkokulu',
  // FINDIKLI
  'RİZE - FINDIKLI - Aksu Atatürk Ortaokulu',
  'RİZE - FINDIKLI - Arılı Ortaokulu',
  'RİZE - FINDIKLI - Çağlayan Osman Hacıalioğlu Ortaokulu',
  'RİZE - FINDIKLI - Fındıklı 15 Temmuz Şehitleri Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - FINDIKLI - Fındıklı TOBB Anadolu İmam Hatip Lisesi',
  'RİZE - FINDIKLI - İbn-i Sina Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - FINDIKLI - Muammer Çiçekoğlu Ortaokulu',
  'RİZE - FINDIKLI - 11 Mart İlkokulu',
  'RİZE - FINDIKLI - Aksu Atatürk İlkokulu',
  'RİZE - FINDIKLI - Arılı İlkokulu',
  'RİZE - FINDIKLI - Çağlayan Osman Hacıalioğlu İlkokulu',
  'RİZE - FINDIKLI - FINDIKLI İLKOKULU',
  'RİZE - FINDIKLI - Sümer İlkokulu',
  // GÜNEYSU
  'RİZE - GÜNEYSU - Osman Erkan Kız Anadolu İmam Hatip Lisesi',
  'RİZE - GÜNEYSU - Borsa İstanbul Ortaokulu',
  'RİZE - GÜNEYSU - Güneysu Şehit Kemal Mutlu Fen Lisesi',
  'RİZE - GÜNEYSU - Güneysu Spor Lisesi',
  'RİZE - GÜNEYSU - Kaptan Ahmet Erdoğan Anadolu İmam Hatip Lisesi',
  'RİZE - GÜNEYSU - Güneysu İmam Hatip Ortaokulu',
  'RİZE - GÜNEYSU - Güneysu Anadolu Lisesi',
  'RİZE - GÜNEYSU - Adacami İlkokulu',
  'RİZE - GÜNEYSU - ÖZEL BİLGE İLKOKULU',
  'RİZE - GÜNEYSU - ÖZEL GÜNEYSU OKULLARI İLKOKULU',
  'RİZE - GÜNEYSU - ÖZEL GÜNEYSU OKULLARI ORTAOKULU',
  'RİZE - GÜNEYSU - Güneysu İlkokulu',
  'RİZE - GÜNEYSU - Kıbledağı Şehit Metin Çetin İlkokulu',
  'RİZE - GÜNEYSU - Ulucami İlkokulu',
  // HEMŞİN
  'RİZE - HEMŞİN - MERKEZ ORTAOKULU',
  'RİZE - HEMŞİN - Hemşin Çok Programlı Anadolu Lisesi',
  'RİZE - HEMŞİN - MERKEZ İLKOKULU',
  // İKİZDERE
  'RİZE - İKİZDERE - İkizdere Anadolu İmam Hatip Lisesi',
  'RİZE - İKİZDERE - ATATÜRK ORTAOKULU',
  'RİZE - İKİZDERE - Fazliye Hüseyin Turanlı Çok Programlı Anadolu Lisesi',
  'RİZE - İKİZDERE - ATATÜRK İLKOKULU',
  // İYİDERE
  'RİZE - İYİDERE - Merkez Ortaokulu',
  'RİZE - İYİDERE - Çiftlik Ortaokulu',
  'RİZE - İYİDERE - Hazar Çaysan Ortaokulu',
  'RİZE - İYİDERE - İyidere Anadolu Lisesi',
  'RİZE - İYİDERE - İyidere İmam Hatip Ortaokulu',
  'RİZE - İYİDERE - İYİDERE MESLEKİ VE TEKNİK ANADOLU LİSESİ',
  'RİZE - İYİDERE - Büyükçiftlik İlkokulu',
  'RİZE - İYİDERE - Hazar Çaysan İlkokulu',
  'RİZE - İYİDERE - Merkez İlkokulu',
  // KALKANDERE
  'RİZE - KALKANDERE - Kalkandere Anadolu İmam Hatip Lisesi',
  'RİZE - KALKANDERE - Şehit Fikret Metin Öztürk Çok Programlı Anadolu Lisesi',
  'RİZE - KALKANDERE - ORMANLI ORTAOKULU',
  'RİZE - KALKANDERE - YOLBAŞI ORTAOKULU',
  'RİZE - KALKANDERE - ÇAYIRLI ORTAOKULU',
  'RİZE - KALKANDERE - ATATÜRK ORTAOKULU',
  'RİZE - KALKANDERE - DAĞDİBİ ORTAOKULU',
  'RİZE - KALKANDERE - ATATÜRK İLKOKULU',
  'RİZE - KALKANDERE - ÇAYIRLI İLKOKULU',
  'RİZE - KALKANDERE - DAĞDİBİ İLKOKULU',
  'RİZE - KALKANDERE - ORMANLI İLKOKULU',
  'RİZE - KALKANDERE - YOLBAŞI İLKOKULU',
  // MERKEZ
  'RİZE - MERKEZ - Ambarlık Ortaokulu',
  'RİZE - MERKEZ - Gülbahar Hatun Kız Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - Ekrem Orhon Turizm Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - Elmalı Ortaokulu',
  'RİZE - MERKEZ - Kendirli Şehit Azim ÖZDEMİR Ortaokulu',
  'RİZE - MERKEZ - Merkez Atatürk Ortaokulu',
  'RİZE - MERKEZ - Rize Türkiye Odalar ve Borsalar Birliği Fen Lisesi',
  'RİZE - MERKEZ - Rize Sosyal Bilimler Lisesi',
  'RİZE - MERKEZ - Tevfik İleri Anadolu Lisesi',
  'RİZE - MERKEZ - Tevfik İleri Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - Rize Merkez Ticaret Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - Rize Anadolu Lisesi',
  'RİZE - MERKEZ - Rize Anadolu İmam Hatip Lisesi',
  'RİZE - MERKEZ - Taşlıdere Gazi Ortaokulu',
  'RİZE - MERKEZ - Ömer Halaç İşitme Engelliler Ortaokulu',
  'RİZE - MERKEZ - Veliköy Uzun Mustafa Kopuz Ortaokulu',
  'RİZE - MERKEZ - Kasarcılar Ortaokulu',
  'RİZE - MERKEZ - Hasan Kemal Yardımcı Denizcilik Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - Kömürcüler Ortaokulu',
  'RİZE - MERKEZ - Çaykur Ortaokulu',
  'RİZE - MERKEZ - Reşadiye Zihni Derin Ortaokulu',
  'RİZE - MERKEZ - Şehit Nedim ÇALIK Ortaokulu',
  'RİZE - MERKEZ - Fatih Anadolu Lisesi',
  'RİZE - MERKEZ - Mehmet Akif Ersoy Ortaokulu',
  'RİZE - MERKEZ - Ali Metin Kazancı Rize Lisesi',
  'RİZE - MERKEZ - Şehit Murat Çalışkaner İmam Hatip Ortaokulu',
  'RİZE - MERKEZ - Karasu Ortaokulu',
  'RİZE - MERKEZ - Çay Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - 100. Yıl Cumhuriyet Ortaokulu',
  'RİZE - MERKEZ - Rize İmam Hatip Ortaokulu',
  'RİZE - MERKEZ - Kendirli Şehit Soner Fazlıoğlu Anadolu İmam Hatip Lisesi',
  'RİZE - MERKEZ - Ortapazar Ortaokulu',
  'RİZE - MERKEZ - Hüseyin Yardımcı Ortaokulu',
  'RİZE - MERKEZ - Rize Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - MERKEZ - Dörtyol Şehit Halil Sadıkoğlu Ortaokulu',
  'RİZE - MERKEZ - Pazarköy Hafız Ali Usta Ortaokulu',
  'RİZE - MERKEZ - Mahmut Celalettin ÖKTEN İmam Hatip Ortaokulu',
  'RİZE - MERKEZ - Hasan Sağır İmam Hatip Ortaokulu',
  'RİZE - MERKEZ - Şehit Onur Kılıç Kız Anadolu İmam Hatip Lisesi',
  'RİZE - MERKEZ - Şehit Erhan Dural Kız Anadolu İmam Hatip Lisesi',
  'RİZE - MERKEZ - FATİH ORTAOKULU',
  'RİZE - MERKEZ - BOĞAZ ORTAOKULU',
  'RİZE - MERKEZ - Küçükçayır Ortaokulu',
  'RİZE - MERKEZ - Gündoğdu 29 Ekim Ortaokulu',
  'RİZE - MERKEZ - Ömer Halaç Özel Eğitim Meslek Lisesi',
  'RİZE - MERKEZ - Nuri Pakdil İmam Hatip Ortaokulu',
  'RİZE - MERKEZ - AMBARLIK İLKOKULU',
  'RİZE - MERKEZ - ZİYA GÖKALP İLKOKULU',
  'RİZE - MERKEZ - METİN BOSTANCIOGLU İLKOKULU',
  'RİZE - MERKEZ - PETROL OFİSİ İLKOKULU',
  'RİZE - MERKEZ - MEHMETÇİK İLKOKULU',
  'RİZE - MERKEZ - VAKIFBANK İLKOKULU',
  'RİZE - MERKEZ - Kurtuluş İlkokulu',
  'RİZE - MERKEZ - Türkiye Odalar ve Borsalar Birliği İlkokulu',
  'RİZE - MERKEZ - Doğuşçay İlkokulu',
  'RİZE - MERKEZ - Çay İlkokulu',
  'RİZE - MERKEZ - ÖZEL RİZE ANADOLU İLKOKULU',
  'RİZE - MERKEZ - ÖZEL RİZE ANADOLU ORTAOKULU',
  'RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ ANADOLU LİSESİ',
  'RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ FEN LİSESİ',
  'RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ İLKOKULU',
  'RİZE - MERKEZ - ÖZEL RİZE BAHÇEŞEHİR KOLEJİ ORTAOKULU',
  'RİZE - MERKEZ - ÖZEL RİZE ÇÖZÜM ANADOLU LİSESİ',
  'RİZE - MERKEZ - ÖZEL RİZE ÇÖZÜM İLKOKULU',
  'RİZE - MERKEZ - ÖZEL RİZE ÇÖZÜM ORTAOKULU',
  'RİZE - MERKEZ - ÖZEL RİZE POYRAZ ANADOLU LİSESİ',
  'RİZE - MERKEZ - ÖZEL RİZE POYRAZ FEN LİSESİ',
  'RİZE - MERKEZ - ÖZEL RİZE POYRAZ ORTAOKULU',
  'RİZE - MERKEZ - Çiftekavak Polis Amca İlkokulu',
  'RİZE - MERKEZ - Denizciler İlkokulu',
  'RİZE - MERKEZ - Dörtyol Şehit Halil Sadıkoğlu İlkokulu',
  'RİZE - MERKEZ - Elmalı İlkokulu',
  'RİZE - MERKEZ - Gündoğdu 29 Ekim İlkokulu',
  'RİZE - MERKEZ - Hüseyin Yardımcı İlkokulu',
  'RİZE - MERKEZ - İstiklal İlkokulu',
  'RİZE - MERKEZ - Karasu İlkokulu',
  'RİZE - MERKEZ - Kasarcılar İlkokulu',
  'RİZE - MERKEZ - Kendirli Şehit Azim ÖZDEMİR İlkokulu',
  'RİZE - MERKEZ - Küçükçayır İlkokulu',
  'RİZE - MERKEZ - Muradiye İlkokulu',
  'RİZE - MERKEZ - Ömer Halaç İşitme Engelliler İlkokulu',
  'RİZE - MERKEZ - Pazarköy Hafız Ali Usta İlkokulu',
  'RİZE - MERKEZ - Pehlivantaşı İlkokulu',
  'RİZE - MERKEZ - Şehit Nedim ÇALIK İlkokulu',
  'RİZE - MERKEZ - Şevket Yardımcı İlkokulu',
  'RİZE - MERKEZ - Taşköprü Atatürk İlkokulu',
  'RİZE - MERKEZ - Taşlıdere Gazi İlkokulu',
  'RİZE - MERKEZ - Vakıflar İlkokulu',
  'RİZE - MERKEZ - Veliköy Uzun Mustafa Kopuz İlkokulu',
  // PAZAR
  'RİZE - PAZAR - FUAT ERGENÇ ORTAOKULU',
  'RİZE - PAZAR - Pazar Anadolu İmam Hatip Lisesi',
  'RİZE - PAZAR - Pazar Kız Kulesi Kız Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - PAZAR - Necat Sağbaş Anadolu Lisesi',
  'RİZE - PAZAR - Pazar Fen Lisesi',
  'RİZE - PAZAR - Pazar 10 Mart Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - PAZAR - Pazar Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - PAZAR - Ahmet Tahtakılıç Ortaokulu',
  'RİZE - PAZAR - HAMİDİYE ORTAOKULU',
  'RİZE - PAZAR - VALİ ERDAL ATA ORTAOKULU',
  'RİZE - PAZAR - TOPLU KONUT İDARESİ BAŞKANLIĞI ORTAOKULU',
  'RİZE - PAZAR - Haberal Vakfı Yaşar ve MedineHaberal Ortaokulu',
  'RİZE - PAZAR - AKTEPE ORTAOKULU',
  'RİZE - PAZAR - ATATÜRK ANADOLU LİSESİ',
  'RİZE - PAZAR - Pazar Şehit Murat Naiboğlu Sivil Havacılık Mesleki ve Teknik Anadolu Lisesi',
  'RİZE - PAZAR - Ahmet Mesut Yılmaz İlkokulu',
  'RİZE - PAZAR - AKTEPE İLKOKULU',
  'RİZE - PAZAR - ÖZEL RİZE PAZAR MEKTEBİM İLKOKULU',
  'RİZE - PAZAR - ÖZEL ÇÖZÜM FEN LİSESİ',
  'RİZE - PAZAR - ÖZEL ÇÖZÜM İLKOKULU',
  'RİZE - PAZAR - ÖZEL ÇÖZÜM ORTAOKULU',
  'RİZE - PAZAR - ÖZEL PAZAR AÇI ANADOLU LİSESİ',
  'RİZE - PAZAR - FUAT ERGENÇ İLKOKULU',
  'RİZE - PAZAR - HAMİDİYE İLKOKULU',
  'RİZE - PAZAR - HÜSEYİN SARIOĞLU İLKOKULU',
  'RİZE - PAZAR - TOPLU KONUT İDARESİ BAŞKANLIĞI İLKOKULU',
  'RİZE - PAZAR - VALİ ERDAL ATA İLKOKULU',
  'RİZE - PAZAR - Veysel Vardal İlkokulu',
]
